name: Production Pipeline
on:
  push:
    tags:
      - release-*
env:
  IMAGE_TAG: latest
  ECR_REGISTRY: dockerhub.com
  ECR_REPOSITORY: achallenge
jobs:
  build:
    environment: production
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: package
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          # docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  deploy:
    environment: production
    needs: [build]
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: package
        run: |
          echo "deploying"
